all:
  children:
    docker_hosts:
      hosts:
        docker-services:
          ansible_host: "{{ lookup('env', 'VPS_IP') | default('127.0.0.1', true) }}"
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
